collections:
        albums: 
                output: true
                permalink: /:collection/:categories:output_ext
                title: albums
defaults: 
      - scope: 
          path: ""
          type: albums
        values:
          layout: album
